# On push or open pull request events, this workflow will run jacotest against the OpenJDK JVM.

name: Jacotest / Hotspot JVM on 6 O/Ses

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**.py'
      - '**.txt'
      - '**.yml'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.py'
      - '**.txt'
      - '**.yml'
    branches: [ "main" ]

jobs:

  build_and_test:
    strategy:
      matrix:
        os: [macos-26-intel, macos-latest, ubuntu-24.04-arm, ubuntu-latest, windows-11-arm, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@main
      with:
          go-version: '1.26.x'
          cache: true
          cache-dependency-path: "**/go.sum"
          
    - name: Setup Jacotest
      run: |
        cd src
        go get github.com/mattn/go-sqlite3
        go build -o . -v ./...
        cd ..
        pwd
        ./src/jacotest -h

    - name: Setup JDK, not Windows ARM64
      if: matrix.os != 'windows-11-arm'
      uses: actions/setup-java@main
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Set up JDK on Windows ARM64
      if: matrix.os == 'windows-11-arm'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'           # or 'adopt', 'microsoft', depending
        java-version: '21'                # or whichever you choose
        architecture: 'arm64'             # key: choose arm64

    - name: Run Test Cases
      run: |
        java --version
        javac --version
        ./src/jacotest -c -x -M -t 60 -j hotspot 
        ls -l ./reports

    - name: Run jacotest -r 1 -j hotspot
      run: |
        ./src/jacotest -r 1 -j hotspot

    - name: Run jacotest -r 2 -j hotspot
      run: |
        ./src/jacotest -r 2 -j hotspot
        
    - name: Run jacotest -r 3 -j hotspot
      run: |
        ./src/jacotest -r 3 -j hotspot
        
    - name: Run jacotest -z -v -j hotspot
      run: |
        ./src/jacotest -z -v -j hotspot

