# This workflow will run jacotest against jacobin using the tests from tests.MINI.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Jacotest with Jacobin - full run

on:
  # Run only when manually triggered.
  workflow_dispatch:  

jobs:

  run_jacobin:
    strategy:
      matrix:
        
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main

    - name: Setup Go
      uses: actions/setup-go@main
      with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: "**/go.sum"
          
    - name: Setup for Linux or MacOS
      run: |
        echo "$HOME/go/bin" >> $GITHUB_PATH
      shell: bash
      if: runner.os != 'Windows'

    - name: Setup for Windows
      run: |
        echo "%HOMEPATH%\go\bin" | Out-File -Append -FilePath $env:GITHUB_PATH
      shell: powershell
      if: runner.os == 'Windows'
        
    - name: Setup Jacotest
      run: |
        cd src
        go get
        go install -v .
        cd ..
        jacotest -h

    - name: Setup Jacobin
      run: |
        git clone https://github.com/texadactyl/jacobin
        cd jacobin/src
        go get
        go install -v ./...
        cd ../..
        jacobin --version
        
    - name: Setup JDK
      uses: actions/setup-java@main
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Run Test Cases
      run: |
        java --version
        javac --version
        jacotest -c -x || true

